FROM python:latest

# Switch to app directory
WORKDIR /FrontEnd

# Copy the requirements in to the app
COPY requirements.txt ./

# Install dependencies
RUN pip install -r requirements.txt

# Copy everything else
COPY . .

#Run the python script
ENTRYPOINT [ "python", "-u", "FrontEnd.py" ]

EXPOSE 8093